import { requireSupabaseAdmin } from 'lib/admin-auth';
import { db } from 'hatchable';
export const access='public';
export const methods=['GET','POST','PUT','PATCH','DELETE'];
const base=()=>process.env.SUPABASE_URL;const key=()=>process.env.SUPABASE_SERVICE_ROLE_KEY;const h=()=>({apikey:key(),Authorization:'Bearer '+key()});
async function sb(path,opts={}){const r=await fetch(base()+'/rest/v1/'+path,{...opts,headers:{...h(),...(opts.headers||{})}});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error(typeof d==='string'?d:(d?.message||d?.hint||'Supabase request failed'));return d;}
function safeName(n){return String(n||'image').replace(/[^a-zA-Z0-9._-]/g,'-').slice(0,160)}
function urlToPath(url){const marker='/storage/v1/object/public/portfolio-images/';const i=String(url||'').indexOf(marker);return i<0?'':String(url).slice(i+marker.length)}
async function deleteUrl(url){const path=urlToPath(url);if(!path)return;await fetch(base()+'/storage/v1/object/portfolio-images/'+path,{method:'DELETE',headers:h()}).catch(()=>{});}
async function project(id){const local=(await (async()=>{try{const r=await fetch(base()+'/rest/v1/projects?select=id,title,slug,cover_image_url,hero_image_url&id=eq.'+encodeURIComponent(id)+'&limit=1',{headers:h()});if(r.ok)return await r.json();return []}catch{return []}})())?.[0];if(local)return local;try{const {rows}=await db.query('SELECT id,title,slug,cover_image_url,hero_image_url FROM case_studies WHERE id=$1 LIMIT 1',[id]);const cs=rows[0];if(!cs)return null;const legacy=(await sb('projects?select=id,title,slug,cover_image_url,hero_image_url&slug=eq.'+encodeURIComponent(cs.slug)+'&limit=1'))?.[0];return legacy?{...legacy,_caseStudyId:cs.id,_caseStudy:cs}:null}catch{return null}}
const allowed=['cover','hero','research','chinedu_persona','fatima_persona','storyboard','wireframes','usability_testing','mobile_final_ui','web_final_ui'];
const sectionMap={research:'research',chinedu_persona:'personas',fatima_persona:'personas',storyboard:'process',wireframes:'process',usability_testing:'usability',mobile_final_ui:'final',web_final_ui:'final'};
export default async function(req,res){try{
 const a=await requireSupabaseAdmin(req);if(!a.ok)return res.status(a.status).json({error:a.error});
 if(req.method==='GET'){const id=req.query?.project_id;if(!id)return res.status(400).json({error:'Missing project_id.'});const p=await project(id);if(!p)return res.status(404).json({error:'Case study not found.'});const previewId=req.query?.preview_image_id;if(previewId){const item=(await sb('project_images?select=image_url&id=eq.'+encodeURIComponent(previewId)+'&project_id=eq.'+encodeURIComponent(id)+'&limit=1'))?.[0];if(!item?.image_url)return res.status(404).json({error:'Media preview not found.'});const r=await fetch(item.image_url);if(!r.ok)return res.status(r.status).send('Media preview could not be loaded.');const contentType=r.headers.get('content-type')||'application/octet-stream';res.setHeader('Content-Type',contentType);res.setHeader('Cache-Control','private, max-age=300');return res.send(Buffer.from(await r.arrayBuffer()));}const previewFixed=req.query?.preview_fixed;if(previewFixed&&['cover','hero'].includes(previewFixed)){const url=previewFixed==='cover'?p.cover_image_url:p.hero_image_url;if(!url)return res.status(404).send('Media preview not found.');const r=await fetch(url);if(!r.ok)return res.status(r.status).send('Media preview could not be loaded.');const contentType=r.headers.get('content-type')||'application/octet-stream';res.setHeader('Content-Type',contentType);res.setHeader('Cache-Control','private, max-age=300');return res.send(Buffer.from(await r.arrayBuffer()));}const [images,sections]=await Promise.all([sb('project_images?select=*&project_id=eq.'+encodeURIComponent(id)+'&order=display_order.asc,created_at.asc'),sb('case_study_sections?select=id,title,section_type,display_order&project_id=eq.'+encodeURIComponent(id)+'&order=display_order.asc')]);return res.json({project:p,images,sections});}
 if(req.method==='POST'){
  const action=req.body?.action;
  if(action==='prepare_upload'){
   const id=req.body?.project_id;const filename=req.body?.filename;const contentType=String(req.body?.content_type||'application/octet-stream').toLowerCase();const replaceFixed=req.body?.replace_fixed;const replaceImageId=req.body?.replace_image_id;
   const supportedImage=['image/png','image/jpeg','image/webp','image/gif','image/svg+xml'];const supportedVideo=['video/mp4','video/webm','video/quicktime'];
   if(!id)return res.status(400).json({error:'Please choose a case study.'});if(!filename)return res.status(400).json({error:'Please choose a file.'});if(!supportedImage.includes(contentType)&&!supportedVideo.includes(contentType))return res.status(400).json({error:'Unsupported media type. Use PNG, JPG, WebP, GIF, SVG, MP4, WebM, or MOV.'});
   const p=await project(id);if(!p)return res.status(404).json({error:'Case study not found.'});
   if(replaceFixed&&!['cover','hero'].includes(replaceFixed))return res.status(400).json({error:'Invalid replacement target.'});
   if(replaceImageId){const existing=(await sb('project_images?select=id,project_id&id=eq.'+encodeURIComponent(replaceImageId)+'&limit=1'))?.[0];if(!existing||existing.project_id!==id)return res.status(404).json({error:'Media item not found.'});}
   const path=`portfolio/${p.slug}/${Date.now()}-${safeName(filename)}`;
   // Supabase signed-upload routes require the bucket name before the object path.
   // The previous implementation omitted it, causing "The related resource does not exist".
   const signed=await fetch(base()+'/storage/v1/object/upload/sign/portfolio-images/'+path,{method:'POST',headers:{...h(),'Content-Type':'application/json'},body:JSON.stringify({upsert:true})});
   const signedText=await signed.text();let signedData=null;try{signedData=signedText?JSON.parse(signedText):null}catch{signedData=signedText}
   if(!signed.ok)throw new Error(typeof signedData==='string'?signedData:(signedData?.message||signedData?.error||signedData?.statusCode||'Could not create a signed upload URL.'));
   if(!signedData?.url)throw new Error('Supabase did not return a signed upload URL.');
   const signedPath=String(signedData?.url||'');if(!signedPath)throw new Error('Supabase did not return a signed upload URL.');const signedUrl=new URL(signedPath.startsWith('/storage/v1/')?base()+signedPath:base()+'/storage/v1'+(signedPath.startsWith('/')?signedPath:'/'+signedPath));return res.json({signedUrl:signedUrl.toString(),path,publicUrl:base()+'/storage/v1/object/public/portfolio-images/'+path,contentType,projectId:id,replaceFixed:replaceFixed||null,replaceImageId:replaceImageId||null});
  }
  if(action==='finalize_upload'){
   const id=req.body?.project_id;const url=String(req.body?.url||'');const type=req.body?.asset_type;const alt=String(req.body?.alt_text||'');const caption=String(req.body?.caption||'');const order=Math.max(0,Number(req.body?.display_order||0));const replaceFixed=req.body?.replace_fixed;const replaceImageId=req.body?.replace_image_id;
   if(!id||!url)return res.status(400).json({error:'Missing uploaded media details.'});if(!url.startsWith(base()+'/storage/v1/object/public/portfolio-images/'))return res.status(400).json({error:'Invalid uploaded media URL.'});const p=await project(id);if(!p)return res.status(404).json({error:'Case study not found.'});
   if(replaceFixed){if(!['cover','hero'].includes(replaceFixed))return res.status(400).json({error:'Invalid replacement target.'});const field=replaceFixed==='cover'?'cover_image_url':'hero_image_url';const old=p[field]||'';const d=await sb('projects?id=eq.'+encodeURIComponent(id),{method:'PATCH',headers:{...h(),'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify({[field]:url,updated_at:new Date().toISOString()})});await deleteUrl(old);return res.json({kind:replaceFixed,url,project:d?.[0]||null});}
   if(replaceImageId){const existing=(await sb('project_images?select=*&id=eq.'+encodeURIComponent(replaceImageId)+'&limit=1'))?.[0];if(!existing||existing.project_id!==id)return res.status(404).json({error:'Media item not found.'});const d=await sb('project_images?id=eq.'+encodeURIComponent(replaceImageId),{method:'PATCH',headers:{...h(),'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify({image_url:url})});await deleteUrl(existing.image_url);return res.json({kind:'gallery',url,image:d?.[0]||null});}
   if(!allowed.includes(type))return res.status(400).json({error:'Invalid asset type.'});const sectionType=sectionMap[type];const sections=await sb('case_study_sections?select=id&project_id=eq.'+encodeURIComponent(id)+'&section_type=eq.'+encodeURIComponent(sectionType)+'&order=display_order.asc&limit=1');const section=sections?.[0];if(!section)return res.status(400).json({error:'No matching case-study section exists for '+type+'. Add that section first.'});const row={project_id:id,section_id:section.id,image_url:url,image_type:type,alt_text:alt,caption,display_order:order};const created=await sb('project_images',{method:'POST',headers:{...h(),'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify(row)});return res.status(201).json({kind:'gallery',url,image:created?.[0]||null});
  }
  const file=req.files?.find(x=>x.field==='file')||req.files?.[0];const id=req.body?.project_id;const replaceFixed=req.body?.replace_fixed;const replaceImageId=req.body?.replace_image_id;
  if(replaceFixed||replaceImageId){
   if(!file)return res.status(400).json({error:'Please choose a replacement file.'});
   const mime=String(file.contentType||'').toLowerCase();const supportedImage=['image/png','image/jpeg','image/webp','image/gif','image/svg+xml'];const supportedVideo=['video/mp4','video/webm','video/quicktime'];if(!supportedImage.includes(mime)&&!supportedVideo.includes(mime))return res.status(400).json({error:'Unsupported media type. Use PNG, JPG, WebP, GIF, SVG, MP4, WebM, or MOV.'});
   if(replaceFixed){
    if(!id||!['cover','hero'].includes(replaceFixed))return res.status(400).json({error:'Invalid replacement target.'});
    const p=await project(id);if(!p)return res.status(404).json({error:'Case study not found.'});const field=replaceFixed==='cover'?'cover_image_url':'hero_image_url';const old=p[field]||'';const path=`portfolio/${p.slug}/${Date.now()}-${safeName(file.filename)}`;const upload=await fetch(base()+'/storage/v1/object/portfolio-images/'+path,{method:'POST',headers:{...h(),'Content-Type':file.contentType||'application/octet-stream','x-upsert':'true'},body:file.buffer});if(!upload.ok)throw new Error('Supabase Storage upload failed: '+await upload.text());const url=base()+'/storage/v1/object/public/portfolio-images/'+path;const d=await sb('projects?id=eq.'+encodeURIComponent(id),{method:'PATCH',headers:{...h(),'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify({[field]:url,updated_at:new Date().toISOString()})});await deleteUrl(old);return res.json({kind:replaceFixed,url,project:d?.[0]||null});
   }
   const existing=(await sb('project_images?select=*&id=eq.'+encodeURIComponent(replaceImageId)+'&limit=1'))?.[0];if(!existing)return res.status(404).json({error:'Media item not found.'});const p=await project(existing.project_id);if(!p)return res.status(404).json({error:'Case study not found.'});const path=`portfolio/${p.slug}/${Date.now()}-${safeName(file.filename)}`;const upload=await fetch(base()+'/storage/v1/object/portfolio-images/'+path,{method:'POST',headers:{...h(),'Content-Type':file.contentType||'application/octet-stream','x-upsert':'true'},body:file.buffer});if(!upload.ok)throw new Error('Supabase Storage upload failed: '+await upload.text());const url=base()+'/storage/v1/object/public/portfolio-images/'+path;const d=await sb('project_images?id=eq.'+encodeURIComponent(replaceImageId),{method:'PATCH',headers:{...h(),'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify({image_url:url})});await deleteUrl(existing.image_url);return res.json({kind:'gallery',url,image:d?.[0]||null});
  }
  const type=req.body?.asset_type;const alt=req.body?.alt_text||'';const caption=req.body?.caption||'';const order=Math.max(0,Number(req.body?.display_order||0));if(!file)return res.status(400).json({error:'Please choose a PNG, JPG, WebP, GIF, SVG, MP4, WebM, or MOV file.'});if(!id)return res.status(400).json({error:'Please choose a case study.'});if(!allowed.includes(type))return res.status(400).json({error:'Invalid asset type.'});const mime=String(file.contentType||'').toLowerCase();const supportedImage=['image/png','image/jpeg','image/webp','image/gif','image/svg+xml'];const supportedVideo=['video/mp4','video/webm','video/quicktime'];if(!supportedImage.includes(mime)&&!supportedVideo.includes(mime))return res.status(400).json({error:'Unsupported media type. Use PNG, JPG, WebP, GIF, SVG, MP4, WebM, or MOV.'});const p=await project(id);if(!p)return res.status(404).json({error:'Case study not found.'});const path=`portfolio/${p.slug}/${Date.now()}-${safeName(file.filename)}`;const upload=await fetch(base()+'/storage/v1/object/portfolio-images/'+path,{method:'POST',headers:{...h(),'Content-Type':file.contentType||'image/jpeg','x-upsert':'true'},body:file.buffer});if(!upload.ok)throw new Error('Supabase Storage upload failed: '+await upload.text());const url=base()+'/storage/v1/object/public/portfolio-images/'+path;
  if(type==='cover'||type==='hero'){const field=type==='cover'?'cover_image_url':'hero_image_url';const old=p[field];const d=await sb('projects?id=eq.'+encodeURIComponent(id),{method:'PATCH',headers:{...h(),'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify({[field]:url,updated_at:new Date().toISOString()})});await deleteUrl(old);return res.status(201).json({kind:type,url,project:d?.[0]||null});}
  const sectionType=sectionMap[type];const sections=await sb('case_study_sections?select=id&project_id=eq.'+encodeURIComponent(id)+'&section_type=eq.'+encodeURIComponent(sectionType)+'&order=display_order.asc&limit=1');const section=sections?.[0];if(!section)return res.status(400).json({error:'No matching case-study section exists for '+type+'. Add that section first.'});
  const row={project_id:id,section_id:section.id,image_url:url,image_type:type,alt_text:alt,caption,display_order:order};const created=await sb('project_images',{method:'POST',headers:{...h(),'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify(row)});return res.status(201).json({kind:'gallery',url,image:created?.[0]||null});
 }
 const b=req.body||{};
 if(req.method==='PUT')return res.status(405).json({error:'Use the direct upload flow to replace media.'});
 if(req.method==='PATCH'){if(!b.id)return res.status(400).json({error:'Missing image id.'});const row={};if(b.display_order!==undefined)row.display_order=Math.max(0,Number(b.display_order)||0);if(b.alt_text!==undefined)row.alt_text=String(b.alt_text);if(b.caption!==undefined)row.caption=String(b.caption);const d=await sb('project_images?id=eq.'+encodeURIComponent(b.id),{method:'PATCH',headers:{...h(),'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify(row)});return res.json(d?.[0]||d);}
 if(req.method==='DELETE'){
  if(b.fixed&&b.project_id){const p=await project(b.project_id);const field=b.fixed==='cover'?'cover_image_url':'hero_image_url';if(!['cover','hero'].includes(b.fixed))return res.status(400).json({error:'Invalid fixed image.'});const old=p?.[field]||'';await sb('projects?id=eq.'+encodeURIComponent(b.project_id),{method:'PATCH',headers:{...h(),'Content-Type':'application/json'},body:JSON.stringify({[field]:'',updated_at:new Date().toISOString()})});await deleteUrl(old);return res.json({ok:true});}
  if(!b.id)return res.status(400).json({error:'Missing image id.'});const existing=(await sb('project_images?select=image_url&id=eq.'+encodeURIComponent(b.id)+'&limit=1'))?.[0];await sb('project_images?id=eq.'+encodeURIComponent(b.id),{method:'DELETE'});await deleteUrl(existing?.image_url);return res.json({ok:true});
 }
 return res.status(405).json({error:'Method not allowed'});
}catch(e){return res.status(500).json({error:e.message||'Media operation failed.'});}}